/*
    I want to analyse trip performance by vendor
    to compare how the two taxi companies perform
    against each other in terms of distance,
    fares and customer tipping behaviour.
    Vendor 1 = Creative Mobile Technologies
    Vendor 2 = VeriFone Inc
*/

SELECT
    -- Convert vendor ID to company name
    CASE VendorID
        WHEN 1 THEN 'Creative Mobile Technologies'
        WHEN 2 THEN 'VeriFone Inc'
        ELSE 'Unknown'
    END AS Vendor_Name,

    -- Count total trips per vendor
    COUNT(*) AS Total_Trips,

    -- Average distance per trip
    ROUND(AVG(trip_distance), 2) AS Avg_Distance_Miles,

    -- Average base fare per trip
    ROUND(AVG(fare_amount), 2) AS Avg_Fare,

    -- Average tip per trip
    ROUND(AVG(tip_amount), 2) AS Avg_Tip,

    -- Average total amount per trip
    ROUND(AVG(total_amount), 2) AS Avg_Total,

    -- Total revenue generated by vendor
    ROUND(SUM(total_amount), 2) AS Total_Revenue

FROM `nyc-yellow-taxi-record-495915.nyc_dataset.nyc_taxi_clean`

-- Group by vendor
GROUP BY VendorID

-- Show highest revenue first
ORDER BY Total_Revenue DESC